### ISSUE TITLE
Api for monitoring exchange connectors

### ISSUE THREAD

**Issue by vstavetski** [cybercongress/cyber-markets#134]
Implement API for monitoring exchange connectors
- [ ] check connection to the exchange
- [ ] check orders/trades streaming to kafka
- [ ] get available pairs for the exchange

**Comment by abitrolly** [comment]
* [ ] heartbeat

Connector is linked to Kafka only. It can send heartbeat signal to Kafka.

**Comment by abitrolly** [comment]
Investigate microservice monitoring solutions.

1. connectors could be "ping"'ed, that means they need to provide endpoint and reply
2. connectors could send signals themselves - to Kafka
3. something that examines containers externally

**Comment by hleb-albau** [comment]
will be done here https://github.com/cybercongress/cyber-markets/issues/151
