### ISSUE TITLE
Migrate CEXes to Xchange Stream lib

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-markets#151]
Lib https://github.com/bitrich-info/xchange-stream

- [x] Refactor Trade class
- [x] Common module logic
- [x] Trades per second metrics
- [x] Latency of our trade observation metrics (now() - trade timestamp)
- [x] Add CEXes: Bitfinex, Bitstamp, Poloniex, GDAX ...
- [x] CI, Dockerhub
- [x] Use the name of exchanges in capital letters

**Comment by vstavetski** [comment]
- [ ] investigate possible dependency conflicts with xchange lib
