### ISSUE TITLE
Add knowledge cybernode/components/markets page 

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-markets#156]
- [x] Create same page as search component.
- [x] Remove repo wiki, Move home wiki to knowledge

**Comment by 21xhipster** [comment]
@vstavetski Please reference a commit before closing

**Comment by vstavetski** [comment]
There is the [commit](https://github.com/cybercongress/knowledge/pull/7/commits/a5fd135b4fab886db40ee8083333a959366c1665)
